

export const Tkinter_TO_WEB_CURSOR_MAPPING = {
    
    "arrow": "default",
    "circle": "wait",
    "clock": "wait",
    "cross": "crosshair",
    "dotbox": "not-allowed",
    "exchange": "alias",
    "fleur": "move",
    "heart": "default", // mapping doesn't exist
    "man": "default",
    "mouse": "default",
    "pirate": "default",
    "plus": "zoom-in",
    "shuttle": "default",
    "sizing": "se-resize",
    "spider": "default",
    "spraycan": "default",
    "star": "default",
    "target": "cell",
    "tcross": "crosshair",
    "trek": "default",
    "watch": "wait",
    "X_cursor": "not-allowed",
    "bottom_left_corner": "sw-resize",
    "bottom_right_corner": "se-resize",
    "bottom_side": "s-resize",
    "top_left_corner": "nw-resize",
    "top_right_corner": "ne-resize",
    "top_side": "n-resize",
    "left_side": "w-resize",
    "right_side": "e-resize",
    "hand1": "pointer",
    "hand2": "pointer",
    "sb_h_double_arrow": "ew-resize",
    "sb_v_double_arrow": "ns-resize",
    "center_ptr": "default",
    "question_arrow": "help",
    "umbrella": "default",
    "pencil": "copy",
}
